package com.example.producktivity.dbs.blacklist;

public enum Category {
    ART_AND_DESIGN, AUGMENTED_REALITY, AUTO_AND_VEHICLES, BEAUTY, BOOKS_AND_REFERENCE, BUSINESS,
    COMICS, COMMUNICATION, DATING, EDUCATION, ENTERTAINMENT, EVENTS, FAMILY, FINANCE, FOOD_AND_DRINK,
    GAME, GOOGLE_CAST, HEALTH_AND_FITNESS, HOUSE_AND_HOME, LIBRARIES_AND_DEMO, LIFESTYLE, PRODUCKTIVITY,
    MAPS_AND_NAVIGATION, MEDICAL, SYSTEM, VIDEO_PLAYERS
}